name: Docker Build and Push

on:
  push:
    branches:
      - main # 当 main 分支有推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # 设置 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: habago
          password: ${{ secrets.DOCKER_TOKEN_HABAGO_FULL }} # Docker Hub 密码，需在仓库设置中添加此 secret

      - name: Read package.json version
        id: read-version
        run: |
          echo "::set-output name=VERSION::$(jq -r .version package.json)"
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Docker 构建上下文
          file: ./Dockerfile # Dockerfile 文件路径
          push: true # 推送到 Docker Hub
          tags: |
            habago/admin:latest
            habago/admin:${{ steps.read-version.outputs.VERSION }}
